/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registersd05;

/**
 *
 * @author Student.admin
 */
public class Regsiter extends javax.swing.JFrame {

    /**
     * Creates new form Regsiter
     */
    public Regsiter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        birthdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        confrimpassword = new javax.swing.JPasswordField();
        registerbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(280, 270));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("REGISTER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 140, 51);

        jLabel2.setText("FIRST NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 70, 16);
        getContentPane().add(firstname);
        firstname.setBounds(50, 110, 230, 30);

        jLabel3.setText("LAST NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 80, 16);
        getContentPane().add(lastname);
        lastname.setBounds(50, 180, 230, 30);

        jLabel4.setText("USER NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 220, 100, 16);
        getContentPane().add(username);
        username.setBounds(50, 240, 230, 30);

        jLabel5.setText("BIRTH DATE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 290, 100, 16);
        getContentPane().add(birthdate);
        birthdate.setBounds(50, 320, 230, 30);

        jLabel6.setText("PASSWORD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 360, 110, 16);
        getContentPane().add(password);
        password.setBounds(50, 382, 230, 30);

        jLabel7.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 420, 140, 16);
        getContentPane().add(confrimpassword);
        confrimpassword.setBounds(50, 442, 230, 30);

        registerbtn.setText("REGISTER");
        getContentPane().add(registerbtn);
        registerbtn.setBounds(100, 482, 140, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regsiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regsiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regsiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regsiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Regsiter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birthdate;
    private javax.swing.JPasswordField confrimpassword;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lastname;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registerbtn;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
